const MIN_BLOCK_SIZE = 15; // DEFAULT MINIMUM BLOCK SIZE FOR APPOINTMENTS (IN MINUTES)
const LOOK_AHEAD_DAYS = 10; // SEARCH FOR AVAILABILITY IN THE NEXT DAYS (IN DAYS)
const APPOINTMENT_CONFIG = {
  WEEKDAY_EXPIRY_HOURS: 24, // EXPIRE AFTER 24 HOURS ON WEEKDAYS
  WEEKEND_EXPIRY_DAY_TIME: '11:00', // EXPIRE ON MONDAY AT 11:00 AM FOR WEEKEND REQUESTS
};
const APP_TIMEZONE = 'America/Lima'; // APPLICATION TIMEZONE (UTC-5)
const BOOKING_STORE_TTL_HOURS = 23; // 23 HOURS TTL FOR BOOKING STORE
const HUMAN_ESCALATION_MESSAGE =
  'Perfecto 🙌 Te paso con la doctora. Puede que esté atendiendo a una mascotita en este momento, pero ni bien termine te escribe por aquí 🐶'; // CONVERSATION FLOW MESSAGES

export {
  MIN_BLOCK_SIZE,
  LOOK_AHEAD_DAYS,
  APPOINTMENT_CONFIG,
  APP_TIMEZONE,
  BOOKING_STORE_TTL_HOURS,
  HUMAN_ESCALATION_MESSAGE,
};
